# Generated by Django 5.0.6 on 2024-05-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_partner_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrecord',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='price_excl_tax',
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='price_retail',
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
    ]
